### ISSUE TITLE
`cvSelectParams` overrides `n_medoids` argument

### ISSUE THREAD

**Issue by nhejazi** [PhilBoileau/scPCA#29]
https://github.com/PhilBoileau/scPCA/blob/master/R/scPCA.R#L414 seems to override its own argument `n_medoids` to the value 8 arbitrarily. This doesn't seem to be the case with the non-cross-validated variant of the function (e.g., https://github.com/PhilBoileau/scPCA/blob/master/R/scPCA.R#L303). Would you mind confirming that this is, in fact, a bug @PhilBoileau?

**Comment by PhilBoileau** [comment]
Yup, this is a bug, `n_medoids` should be set to `n_medoids`.  Thanks for noticing!

**Comment by nhejazi** [comment]
Got it, fixed! Will close issue after incoming PR.
