### ISSUE TITLE
JOSS: natively handling alternative matrix representations

### ISSUE THREAD

**Issue by LTLA** [PhilBoileau/scPCA#40]
It looks like `scPCA::coerceMatrix` collapses sparse matrices to an ordinary matrix. This isn't healthy for memory efficiency or speed when zeroes are unnecessarily stored and processed.

I'm not going to make a big deal about this because it seems that your upstream packages coerce to dense matrices anyway, so it doesn't really make much difference whether you do the right thing for these alternative matrices. However, the proposed use case for scRNA-seq data will not be a strong one if people have to desparsify matrices. A small dataset of 50K cells, 2K HVGs requires almost 1 GB of memory in theory, and practical usage will be several-fold higher due to all the copies. 

You may consider suggesting to the maintainers of your upstream packages to make adjustments to accept sparse matrices (or, in fact, matrices of any representation). e.g., erichson/rSVD#4.

While I'm on this point, your coercion doesn't catch other matrix classes, e.g., `HDF5Matrix` and `DelayedMatrix` objects will just slip through and presumably cause havoc in later parts of the code.

**Comment by PhilBoileau** [comment]
Thank you for pointing this out. That is definitely something that I will get on top of in the near future!

With respect to the `coerceMatrix` function not catching other matrix classes, there is a separate function, `checkArgs`, that is called at the beginning of the `scPCA ` function which performs checks on most of `scPCA`'s inputs. In particular, the target and background datasets' classes are inspected, and an error is thrown if something is off.
