### ISSUE TITLE
n_centers=1 yields a list instead of a matrix for x, rotation

### ISSUE THREAD

**Issue by LTLA** [PhilBoileau/scPCA#45]
Pretty much as the title says. Documentation indicates that I should be getting a matrix out for `x` and `rotation`.

```r
library(scPCA)

# perform cPCA on the simulated data set
out <- scPCA(
   target = toy_df[, 1:30],
   background = background_df,
   penalties = 0,
   n_centers = 1
)

str(out$x)
## List of 8
##  $ : num [1:400, 1:2] -16.46 21.58 1.28 8.85 -6.05 ...
##  $ : num [1:400, 1:2] 3 15.87 8 12.6 4.88 ...
##  $ : num [1:400, 1:2] -5.88 -11.38 -9.8 -11.37 -6.14 ...
##  $ : num [1:400, 1:2] 5.97 10.17 9.92 11.05 6 ...
##  $ : num [1:400, 1:2] -5.18 -4 -3.93 -5.85 -5 ...
##  $ : num [1:400, 1:2] 5.04 3.24 3.47 5.64 4.44 ...
##  $ : num [1:400, 1:2] -2.717 -0.863 -1.044 -3.089 -1.993 ...
##  $ : num [1:400, 1:2] -1.623 -0.161 -0.121 -2.034 -1.109 ...
```

<details>
<summary>Session information</summary>

```
R version 4.0.0 Patched (2020-05-01 r78341)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /home/luna/Software/R/R-4-0-branch-dev/lib/libRblas.so
LAPACK: /home/luna/Software/R/R-4-0-branch-dev/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] scPCA_1.3.1

loaded via a namespace (and not attached):
 [1] cluster_2.1.0       magrittr_1.5        elasticnet_1.3     
 [4] tidyselect_1.1.0    BiocParallel_1.23.2 R6_2.4.1           
 [7] rlang_0.4.7         bibtex_0.4.2.2      stringr_1.4.0      
[10] dplyr_1.0.1         globals_0.12.5      tools_4.0.0        
[13] parallel_4.0.0      data.table_1.13.0   lars_1.2           
[16] ellipsis_0.3.1      matrixStats_0.56.0  digest_0.6.25      
[19] abind_1.4-5         assertthat_0.2.1    tibble_3.0.3       
[22] lifecycle_0.2.0     crayon_1.3.4        purrr_0.3.4        
[25] kernlab_0.9-29      codetools_0.2-16    vctrs_0.3.2        
[28] Rdpack_1.0.0        gbRd_0.4-11         glue_1.4.1         
[31] future.apply_1.6.0  origami_1.0.3       stringi_1.4.6      
[34] compiler_4.0.0      pillar_1.4.6        generics_0.0.2     
[37] future_1.18.0       listenv_0.8.0       pkgconfig_2.0.3    
```
</details>

**Comment by PhilBoileau** [comment]
I just re-read our documentation, and realized that it isn't clear enough with regards to cPCA. To make a long story short, there are two forms of cPCA:

**Comment by PhilBoileau** [comment]
I just re-read the documentation, and realized that the implementations of cPCA aren't very clear. The package implements two flavours of cPCA:

**Comment by LTLA** [comment]
Thanks. I ended up using `n_centers > 1` anyway, I wasn't getting a good correction with `n_centers=1` in a little test where I used one cluster of cells as a control for the rest of the dataset. 

FYI, here's what it looked like with `n_centers=5`, using the WT as the control dataset:

![image](https://user-images.githubusercontent.com/8166669/89497066-6f30ce80-d770-11ea-9536-dc09e3b54ec9.png)

You can see how the cell cycle differences are eliminated in the WT (as one might expect); this did not happen with `n_centers=1`, presumably because the contrast parameter was not well-chosen.

**Comment by PhilBoileau** [comment]
Very interesting! I wonder how many meaningful biological effects were removed, if at all all, from the WT cells when using a subset of WT as a control dataset? If the cell cycle effect is relatively small compared to the meaningful biological effects, then your approach for specifying a control group should work quite well.

Even after contrasting the control and target data, some unwanted variation may remain. This might explain why the cells with induced oncogene expression are still clustered based on cell cycle. I've noticed that sparsifying the loadings often removes these lingering, unwanted effects. I'm going to play around with this dataset over the weekend to see if I can't do just that. I'll keep you posted. In any case, you capture the general issue of selecting a control dataset succinctly in the most recent commit of your PR https://github.com/Bioconductor/OrchestratingSingleCellAnalysis/pull/35.

**Comment by LTLA** [comment]
> I wonder how many meaningful biological effects were removed, if at all all, from the WT cells when using a subset of WT as a control dataset?

Probably something, but I think it's fine; can't make an omelette without breaking a few eggs, so to speak.

I should point out that I cheated a bit because I used all the WT as the control and didn't take them out. Just didn't have enough cells in this particular dataset to afford to be able to take subsets. It is, at least, reassuring that the procedure does remove the cell cycle effect in that group - I assume that this is not an entirely trivial result, given that it occurs in the presence of the oncogene-induced group (so the subtracted covariance matrix isn't just all-zero).

> Even after contrasting the control and target data, some unwanted variation may remain. This might explain why the cells with induced oncogene expression are still clustered based on cell cycle. I've noticed that sparsifying the loadings often removes these lingering, unwanted effects.

I'm not too unhappy with the residual separation; I wouldn't be surprised if the oncogene induction does extra things to the magnitude of the cell cycle effect that wouldn't be captured in the WT. I also tried using the default `penalties` but it took some time and I wasn't that interested in improving the result further to wait for it to finish.

> I'm going to play around with this dataset over the weekend to see if I can't do just that. I'll keep you posted. 

Cool. While you're still enthusiastic about this: I'd just like to be reassured that the nice picture above wasn't a one-off, and that the same approach works with different datasets. Googling around indicates a few possible datasets:

- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7197478/
- A good list here: https://www.nature.com/articles/s41467-017-00039-z/tables/1

If you can find 1-2 good demonstrations, I'll throw them into the book as well. Might even dedicate an entire chapter to it if you can find enough examples to fill it up. (Doesn't even have to be cell cycle-related.)

> **Edit:** If we can assume that the cell-cycle variation is dominated by more meaningful biological effects, then a control might be formed by randomly sampling from both the WT and oncogene expressing cells. The wanted variation will be deflated in the target, but not as much as the unwanted cell cycle variation.

I'm not sure that I follow. Seems like the expectation of the covariance matrix for the randomly sampled control should be pretty close to that of the original target dataset, so you'd just end up wiping out all the variation.

I guess you could assemble the control's covariance matrix in a "blocked" manner. For example, if I had three clusters that should be homogeneous, I could use cells from all three clusters to construct the control covariance matrix while blocking on the cluster assignments to avoid capturing the cluster-based variation. Effectively "averaging out" the variation within each individual cluster to get a more robust estimate of the control covariance.

**Comment by PhilBoileau** [comment]
> Probably something, but I think it's fine; can't make an omelette without breaking a few eggs, so to speak.
> 
> I should point out that I cheated a bit because I used all the WT as the control and didn't take them out. Just didn't have enough cells in this particular dataset to afford to be able to take subsets. It is, at least, reassuring that the procedure does remove the cell cycle effect in that group - I assume that this is not an entirely trivial result, given that it occurs in the presence of the oncogene-induced group (so the subtracted covariance matrix isn't just all-zero).

Sounds good! I guess it doesn't really matter all that much if the end goal is to identify markers in the oncogene-induced group. Whatever variation that remains after taking the difference of the covariance matrices will be driven mostly by that group. Retaining the WT/control group in the visualization is also an interesting idea. As you said, it acts a as a nice diagnostic tool.

> Cool. While you're still enthusiastic about this: I'd just like to be reassured that the nice picture above wasn't a one-off, and that the same approach works with different datasets. Googling around indicates a few possible datasets:
> 
> - https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7197478/
> - A good list here: https://www.nature.com/articles/s41467-017-00039-z/tables/1
> If you can find 1-2 good demonstrations, I'll throw them into the book as well. Might even dedicate an entire chapter to it if you can find enough examples to fill it up. (Doesn't even have to be cell cycle-related.)

Thanks for linking those datasets! I'll start by implementing your suggestions, and then attempt to speed up the (s)cPCA functions. I'll try to get you some completed examples by the end of the week. Hopefully they're favourable. 

> I'm not sure that I follow. Seems like the expectation of the covariance matrix for the randomly sampled control should be pretty close to that of the original target dataset, so you'd just end up wiping out all the variation.
> 
> I guess you could assemble the control's covariance matrix in a "blocked" manner. For example, if I had three clusters that should be homogeneous, I could use cells from all three clusters to construct the control covariance matrix while blocking on the cluster assignments to avoid capturing the cluster-based variation. Effectively "averaging out" the variation within each individual cluster to get a more robust estimate of the control covariance.

Regarding my edit: You're totally right, I should have finished my morning coffee before churning out ideas. Your blocking idea sounds promising, though. I'll look into it some more.

**Comment by PhilBoileau** [comment]
I've finally gotten around to applying cPCA and scPCA (with new bells and whistles) to the dataset used in your example above. I've attached the [.Rmd file and its knitted output](https://github.com/PhilBoileau/scPCA/files/5104797/lun416b.zip). It's largely based off of your original code, but I've included a few (rough) comments.

I've set some time aside over the next few days to apply these contrastive methods to the other datasets that you've mentioned. I'll get back to you then with similar notebooks.

**Comment by LTLA** [comment]
Thanks @PhilBoileau. FYI it has also made its way into the [book](https://osca-dev.bioconductor.org/cell-cycle-assignment.html#using-contrastive-pca).

It seems that a fair bit of effort is involved in choosing an appropriate value for `contrasts`. It may turn out to be sufficient to just set it to a constant like 100... it wouldn't be the first arbitrary constant and it won't be the last.

I had always thought that `contrasts=1` was the most natural choice, if you assume that the uninteresting and interesting variance is additive; but this does not work very well, so I guess I'm missing something.

**Comment by PhilBoileau** [comment]
This conversation has been taken offline, and the original issue has been resolved. I'll close this thread for now.
