### ISSUE TITLE
More flexible handling of clusters

### ISSUE THREAD

**Issue by LTLA** [PhilBoileau/scPCA#47]
It seems that, if I _already_ have some kind of clustering information, I should be able to use that information rather than relying on `scPCA()` to recluster my data. One could imagine a `clusters=` argument or such.

On a related note, it also seems that, if I supply a single value to `contrasts=`, I should not be expected to specify a `n_centers=` value, because I've already chosen the value of the contrastive parameter that I want to use.

**Comment by PhilBoileau** [comment]
Great idea, that `clusters` argument seems very reasonable in the scRNA-seq setting. It'll make the method feel a little less "unsupervised", though.

And good point regarding the `n_centers` argument. I'll fix that while implementing the option for prior clustering info!
