### ISSUE TITLE
RSpectra::eigs_sym occasionally does not return the specified number of eigenvectors

### ISSUE THREAD

**Issue by LTLA** [PhilBoileau/scPCA#50]
In the Zeisel example in the OSCA book chapter, I'm getting errors like:

```
Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent
In addition: Warning message:
In do.call(.Call, args = dot_call_args) :
  only 8 eigenvalue(s) converged, less than k = 10
```

This stems from the fact that `RSpectra::eigs_sym` does not always return the specified `k` eigenvectors when convergence fails for the later eigenvectors, which is highly unfortunate. For the time being, I have hacked around it by specifying a very low `penalties=1e-8` but it may be worth considering what to do in such cases. I didn't feel that the **RSpectra** approach was significantly faster than what was there before, but I don't have timings to support that.

**Comment by PhilBoileau** [comment]
Agh, sorry about that. I'll play around with this example and see what can be done. I might need to include arguments in the `scPCA` function for controlling the precision and max number of iterations of `RSpectra::eigs_sym`.

I'm surprised that you didn't see an increase in computation speed. I found that this approach was about 4 times faster when running cPCA on some simulated scRNA-seq data. I'll test it out on the dataset in the OSCA chapter and get back to you!

**Comment by LTLA** [comment]
Oh, when I say "not significantly faster", I just meant that it didn't finish immediately; as I said, I didn't actually time the difference, because usually I just start doing something else if it's going to take more than a few seconds.
