### ISSUE TITLE
memory allocation problem

### ISSUE THREAD

**Issue by chisin** [PhilBoileau/scPCA#56]
Hello,
thank you for developing scPCA. I am working on a large dataset, of 120 paired samples (60 control/treatment pairs) for ca 50.000 features. No matter how much I downsize my dataset, I keep running into memory allocation problems (even while working on cloud). Also parallel computing is no help, as I get issues with reading from different sources. 
I have two questions:
- is there any way to implement the information that my "background" and "treatment" datasets are paired? would this make the memory usage less intensive?
- would you have any recommendation in terms of parameters (eg clustering method or penalties), for optimising memory usage?

Thank you in advance,

C

**Comment by PhilBoileau** [comment]
Hi @chisin! Unfortunately, there's no way to take into account the paired nature of the treatment and control group. If you're willing to provide some more information on your dataset/analysis, I might be able to guide you better. With that said, here are some generic recommendations to improve the performance of `scPCA`:

1. Reduce the number of features. These methods operate over a special form of the covariance matrix, which in your case is about 50,000x50,000. This is probably the cause of your memory allocation issues. Your best bet is to only consider the most variable features e.g. the top 1,000-2,000 features. Depending on the type of data, this subsetting might also have a denoising effect.
2. If running scPCA, set `alg = 'rand_var_proj'`.
3. Reduce the number of `contrasts` and `penalty` parameters considered.
4. If you haven't already, consider turning your target and background into `DelayedMatrices`.
5. If your treatment groups have subgroups, then you might consider plugging these into the `clusters` argument.

You can find some examples [here (17.5.4)](http://bioconductor.org/books/devel/OSCA/cell-cycle-assignment.html#removing-cell-cycle-effects) and [here](http://bioconductor.org/books/devel/OSCA/messmer-hesc.html). 

Hope this helps!

**Comment by chisin** [comment]
Thank you for your answer! My dataset is a time-course RNAseq, where I sampled each pair of control_vs_treated samples from different individuals (so I need to identify the "treated response", over time, whilst correcting/ignoring the background individual signature). For a start, I was simply using my unprocessed count data - which probably was not a great idea...
I am now trying to implement your suggestions, but I am getting an error when feeding the DelayedMatrix dataset to scPCA function (built with 
```
> sample_Matrix <- DelayedArray(df_sample)
> class(sample_Matrix)
[1] "DelayedMatrix"
attr(,"package")
[1] "DelayedArray"
```
).
If I run the code:
```
> scpca_sam <- scPCA(target = sample_Matrix,
+                    background = background_Matrix, 
+                    n_centers = 2,
+                    penalties = exp(seq(log(0.01), log(0.5), length.out = 3)),
+                    alg = "rand_var_proj",
+                    parallel = F)
Error: tibble::is_tibble(x = target) is not TRUE or target is not a data frame or target is not a matrix or is(object = target, class2 = "dgeMatrix") is not TRUE or is(object = target, class2 = "dgCMatrix") is not TRUE
```

**Comment by PhilBoileau** [comment]
Gotcha. You definitely need to pre-process your data prior to applying the `scPCA`. You might also try performing cPCA prior to scPCA by setting the `penalties` argument to 0.

You'll have to download the development version of the package to access the `DelayedMatrix` functionality -- I should have specified, sorry. On second thought, though, you probably don't need to use `DelayedMatrices` given that you don't have that many observations. A regular matrix or dataframe should do the trick, assuming that you provide a reasonable number of features.

**Comment by chisin** [comment]
Thanks! I am going to try.

**Comment by PhilBoileau** [comment]
Closing due to lack of feedback,
