### ISSUE TITLE
How to extract features contributing most to the eigenvector of interest

### ISSUE THREAD

**Issue by klai001** [PhilBoileau/scPCA#62]
Many thanks for the good work developing this toolkit!
I am a biologist by training that happens to analyse various omics data for my research. Therefore I apologise if this question is too naive- i am interested in using cPCA and trying to identify the features contributing most to variance of the dataset, with my healthy control as background; could you share how can I do so using this package? I presume it's similar to finding genes contributing most to PC1 for standard PCA

**Comment by PhilBoileau** [comment]
Thank you for the kind words!

That's exactly right; genes' contributions to the (sparse) contrastive principal components can be obtained through the same approach used in standard PCA. A tutorial for this is provided in Section 3.4 of the package's [vignette](https://bioconductor.org/packages/devel/bioc/vignettes/scPCA/inst/doc/scpca_intro.html). Examples are also provided in [Boileau et al (2020)](https://academic.oup.com/bioinformatics/article/36/11/3422/5807607).

Please let me know if you have any questions.
